### PR TITLE
Quality of Life changes

### PR DESCRIPTION
**Pull request by yorickdowne**
- WS port now mapped to host and configurable
- Archive or full mode configurable
- Image tag for healthcheck container
- l2geth has a grace period of 3m so it can shut down cleanly no matter how long it's been running
- README shows docker-compose commands to get logs, instead of docker commands
- Variables reordered to flow a little better
- restart pulled out into .env

### CODE REVIEW

**Comment by yorickdowne** [comment]
Draft to understand `REPLICA_HEALTHCHECK__L2GETH_IMAGE_TAG` which is in the kustomize env files. Is that actually in use? If not, I could remove it as port of this QoL change. If it is used, it'd make sense to pull it out to default.env

**Comment by yorickdowne** [comment]
@optimisticben Coming back to this, got busy ... can you comment on the above two variables? If they are not needed in the shared env files I'll remove them, take this PR out of draft, and then the last part are the traefik bits in another PR.

**Comment by yorickdowne** [comment]
Thank you. Will make these changes

**Review by optimisticben — APPROVED** [review]
lgtm!

**Pull request merged**
