### PR TITLE
Added the genesis hash, as required by the Berlin setup script

### PR DESCRIPTION
**Pull request by qbzzt**

### CODE REVIEW

**Comment by optimisticben** [comment]
The hashes are in the shared envs.

https://github.com/optimisticben/op-replica/blob/main/kustomize/replica/envs/kovan/l2geth-replica.env#L14
https://github.com/optimisticben/op-replica/blob/main/kustomize/replica/envs/mainnet/l2geth-replica.env#L17

**Comment by qbzzt** [comment]
Sorry, but it doesn't work.

Command:
```
cat .env | grep -i genesis_hash ; docker-compose logs l2geth-replica | grep -i genesis_hash ; netstat -an | grep LISTEN | grep tcp
```

Output without `L2GETH_GENESIS_HASH` set in `.env`:

```
ori@docker-geth-0-5-11:~/op-replica$ cat .env | grep -i genesis_hash ; docker-compose logs l2geth-replica | grep -i genesis_hash ; netstat -an | grep LISTEN | grep tcp
# L2GETH_GENESIS_HASH=0x361ff81fff4cc71e5f0bf43b0b982f5cfd08d068f730b9a61516fe1fa8fd914a
l2geth-replica_1        | /scripts/check-for-chaindata-berlin.sh: line 30: L2GETH_GENESIS_HASH: parameter not set
l2geth-replica_1        | /scripts/check-for-chaindata-berlin.sh: line 30: L2GETH_GENESIS_HASH: parameter not set
l2geth-replica_1        | /scripts/check-for-chaindata-berlin.sh: line 30: L2GETH_GENESIS_HASH: parameter not set
l2geth-replica_1        | /scripts/check-for-chaindata-berlin.sh: line 30: L2GETH_GENESIS_HASH: parameter not set
l2geth-replica_1        | /scripts/check-for-chaindata-berlin.sh: line 30: L2GETH_GENESIS_HASH: parameter not set
l2geth-replica_1        | /scripts/check-for-chaindata-berlin.sh: line 30: L2GETH_GENESIS_HASH: parameter not set
l2geth-replica_1        | /scripts/check-for-chaindata-berlin.sh: line 30: L2GETH_GENESIS_HASH: parameter not set
l2geth-replica_1        | /scripts/check-for-chaindata-berlin.sh: line 30: L2GETH_GENESIS_HASH: parameter not set
l2geth-replica_1        | /scripts/check-for-chaindata-berlin.sh: line 30: L2GETH_GENESIS_HASH: parameter not set
l2geth-replica_1        | /scripts/check-for-chaindata-berlin.sh: line 30: L2GETH_GENESIS_HASH: parameter not set
l2geth-replica_1        | /scripts/check-for-chaindata-berlin.sh: line 30: L2GETH_GENESIS_HASH: parameter not set
tcp        0      0 0.0.0.0:7878            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp6       0      0 :::7878                 :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN 
```
Output with `L2GETH_GENESIS_HASH` set in `.env`:
```
ori@docker-geth-0-5-11:~/op-replica$ cat .env | grep -i genesis_hash ; docker-compose logs l2geth-replica | grep -i genesis_hash ; netstat -an | grep LISTEN | grep tcp
L2GETH_GENESIS_HASH=0x361ff81fff4cc71e5f0bf43b0b982f5cfd08d068f730b9a61516fe1fa8fd914a
tcp        0      0 0.0.0.0:7878            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:9991            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:9992            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp6       0      0 :::7878                 :::*                    LISTEN     
tcp6       0      0 :::9991                 :::*                    LISTEN     
tcp6       0      0 :::9992                 :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN 
```

**Comment by optimisticben** [comment]
I created a `default-kovan.env` and `default-mainnet.env` which specify the startup script and default env for each network. The default network env contain the required script vars.

Please update your main branch from this repo and let me know if you still have a problem.

**Comment by qbzzt** [comment]
Fixed, thank you.

**Pull request closed without merging**
